install.packages("devtools")
library(devtools)
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("dada2")
biocLite("phyloseq")
biocLite("Rqc")
biocLite("edgeR")
biocLite("DESeq2")
install.packages(c("knitr","ggplot2", "dplyr", "Rmisc", "caTools",  "kableExtra", "Rmisc", "empiricalFDR.DESeq2"))