install.packages("devtools")
library(devtools)
install_version("vegan", version = "2.4-6", repos = "http://cran.us.r-project.org")
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("dada2")
biocLite("phyloseq")
biocLite("Rqc")
install.packages(c("knitr","ggplot2", "dplyr", "Rmisc", "caTools",  "kableExtra"))