---
title: "Micro336 Lab 3"
author: "SEM"
date: "September 12, 2017"
output:
  html_document: default
pdf_document: default
---
  
  This week's questions and your answers:
  

1. How many taxa, samples, variables and taxonomic ranks are represented within the HMP data file used in lab this week? How many are represented when the data was subsetted to focus solely on samples collected from Throat samples?



2. Explain what rarefication is and the purpose of it.


3. Provide a plot showing the number of sequences/OTUs per sample for Throat samples (ensure to trim absent taxa and rarefy to 1000 sequences per sample).



4. Define what alpha and beta diversity is? 



5. Explain why these measures are used in microbial ecology to describe communities of microbes.



6. What are the max and min alpha measures observed in Throat samples? Are there differences between alpha diversity based on where the sequencing was performed (RUNCENTER)? Show your boxplot and provide statistical support for your interpretation.

```{r}


##Example of how to perform statistics to support observed changes in Alpha diversity
##Kruskal-Wallis test for correlation between observed species and RUNCENTER
##alpha_meta_H35_T= combined metadata and alpha summary file

kruskal.test(Observed ~ RUNCENTER, data = alpha_meta_H35_T)
kruskal.test(Shannon ~ RUNCENTER, data = alpha_meta_H35_T)

```


7.	Are there differences in beta diversity across Throat samples based on RUNCENTER? Show and interpret your NMDS plot. Assign a different color to each Run Center.  Provide statistical support for your NMDS plot (Stressplot) and your interpretations.



8.	Do you see differences between statisical results based on ANOSIM vs ADONIS? Explain why you would use one over the other.


##library(knitr)
##knit('Lab3.rmd')
###will make an output file called file.rm
##library(rmarkdown)
##render("Lab3.rmd","html_document")