---
title: "Perm_fire-import"
output: html_document
---

```{r setup, include=FALSE}
library(phyloseq)
perm_fire<-load("~/Micro336-master/Assessment/Dataset-permafrost-fire/permafrost-fire.RData")
#Example - Extracting sample_data
md<-data.frame(sample_data(Tas_rare_phyloseq))
```

```{r}
# Just pick a categorical group that exists in your metadata, doesn't have ot be the one you are using 
dge = phyloseq_to_edgeR(Tas_rare_phyloseq, group="Treatment")
#Grabbing the metadata we want to test 
a<-sample_data(Tas_rare_phyloseq)
#Using the metadata to create a varable called "carbon" describing the continuous metadata we want to test
carbon<-a$diss_org_carb
# Create the design matrix that edgeR needsx = calcNormFactors(dge, method="RLE")

design <-model.matrix(~carbon)


#These are some things edgeR does when running
x = estimateGLMCommonDisp(dge, design)
x = estimateGLMTrendedDisp(dge, design)
x = estimateGLMTagwiseDisp(dge, design)

# Instead of the exact test we did in class, we're applying a generalized linear model to fit our categorical data (carbon) to our OTUs to see how well the abundance of carbon can model the abundace of the OTU
fit <-glmFit(x, design)
lrt <- glmLRT(fit)

# and now you can use the rest of the code from the lab manual to graph it
tt = topTags(lrt, n = nrow(dge$table), adjust.method = "BH", sort.by = "PValue")



```